### ISSUE TITLE
Run other examples other than Viking

### ISSUE THREAD

**Issue by regymm** [fededevi/pingo#6]
Hi, I'm quite interested in this project, but I couldn't find any way to use examples other than the Viking model -- the teapot and cube. 

I tried changing `    Object viking_room;
	viking_room.mesh = &viking_mesh;
`, using mesh_teapot instead of viking_mesh, but resulted in a segfault. 

By the way, I managed to use this program on Linux by changing consolebackend and now I have a rotating Viking model in the Linux terminal. If you are interested I'll clean up my code a bit and send a PR.

**Comment by fededevi** [comment]
I'm on linux too atm so it is kinda hard for me to check right away but did you remove the material from the Object? You can comment everything from line 53 to 60.

On renderer.c:220 the renderer will check if the object has a material and act accordingly, not great code but whatever.. The teapot and cube model do not have texture coordinates so it will crash if the material is set.

Go ahead with the PR, I appreciate it. Consider that if you run this on an embedded linux platform you should be able to directly write to /dev/fb if you write the backend.

**Comment by ustcpetergu** [comment]
Thanks for your reply. The teapot and cube module now works. Though it's extremely small and only looks good after I multiplied all parameters in cube.c by 5 -- don't know what part I got wrong. 

I also added a Linux manual compile script, as I'm not familiar with qmake -- you may want to merge the two or so. 

Btw, I ported it to my RISC-V softcore on FPGA(to test HDMI modules), and got [this](https://t.me/petergulife/144), quite interesting.

**Comment by fededevi** [comment]
Nice stuff! 
In order to change the zoom or position of the camera you'll need to mess with the projection/view matrix.

```
        // PROJECTION MATRIX - Defines the type of projection used
        renderer.camera_projection = mat4Perspective( 1, 250.0,(float)size.x / (float)size.y, 70.0);

        //VIEW MATRIX - Defines position and orientation of the "camera"
        Mat4 v = mat4Translate((Vec3f) { 0,0.7,-7});
        Mat4 rotateDown = mat4RotateX(-0.40); //Rotate around origin/orbit
        renderer.camera_view = mat4MultiplyM(&rotateDown, &v );
```

In order to make the projection bigger you can reduce the FOV on the perspective projection matrix:
`Mat4 mat4Perspective(float near, float far, float aspect, float fov)`
You can reduce the field of view from 70 to 30 to zoom in, but 70-90 is kinda the sweet spot for rendering. 

Or you can move the camera closer to the object with the first view matrix translation.
Mat4 v = mat4Translate((Vec3f) { 0,0.7,-7});

the { 0,0.7,-7} vector gives the position of the camera relative to the origin before the subsequent rotation, you can change it to something like { 0,0.2,-2} if the object is smaller. 

If you checkout older commits (e.g. e53fa0ac4e34fd90e1a2e39bc64481e6cfcdcd5a) there is also an example where a more complex scene with hierarchical transformation is used.

**Comment by ustcpetergu** [comment]
These parameter changes worked -- thanks!
